// js/agent/skills.js
// Skill Registry — the ONLY way to retrieve data from the profile.
// Each skill is a typed function that returns a structured Evidence object.
//
// Skills are NOT called directly. The Retriever executes SkillCalls
// generated by the Planner.
import { LINKS } from "../data/links.js";
import { PROJECTS, PROJECT_READABLE, PROJECT_ORDER } from "../data/projects.js";
import { FILES } from "../data/files.js";
import { getNode, getNeighbors, getByType, getEvidenceForTopic, traverse, skillId } from "./graphStore.js";
import { phraseAwareTokenize } from "../rag/tokenizer.js";

// ---- Evidence factory ----
let _evidenceSeq = 0;
function makeEvidence(skill, data, sourceText = "") {
  return {
    id: `ev_${++_evidenceSeq}_${skill}`,
    skill,
    data,
    source_text: sourceText,
    confidence: 1.0,
    citations: [],
  };
}

// ---- Individual skills ----

export function get_profile() {
  const candidate = getNode("candidate:aravind");
  const attrs = candidate?.attrs || {};
  const data = {
    name: attrs.name || "Aravind E S",
    role: attrs.role || "AI Software Engineer",
    org: attrs.org || "Tata Elxsi",
    location: attrs.location || "Kerala, India",
    status: attrs.status || "Open to full-time AI/ML roles",
  };
  return makeEvidence(
    "get_profile",
    data,
    `${data.name} · ${data.role} @ ${data.org} · ${data.location}`
  );
}

export function get_contact() {
  const data = { email: LINKS.email, phone: LINKS.phone, linkedin: LINKS.linkedin, location: LINKS.location };
  return makeEvidence(
    "get_contact",
    data,
    `email: ${LINKS.email} · phone: ${LINKS.phone} · linkedin: ${LINKS.linkedin}`
  );
}

export function get_experience() {
  const entries = getByType("experience");
  const data = entries.map((e) => {
    // Get projects associated with this experience
    const projectEdges = getNeighbors(e.id).filter((ne) => ne.rel === "WORKED_ON");
    const projects = projectEdges.map((ne) => ne.node?.attrs?.name).filter(Boolean);
    return {
      id: e.id,
      role: e.attrs.role,
      company: e.attrs.company,
      period: e.attrs.period,
      location: e.attrs.location,
      level: e.attrs.level,
      projects,
    };
  });
  const sourceText = data
    .map((d) => `${d.role} @ ${d.company} (${d.period})`)
    .join("; ");
  return makeEvidence("get_experience", data, sourceText);
}

export function get_projects() {
  const data = PROJECT_ORDER.map((name) => {
    const proj = PROJECTS[name];
    const readable = PROJECT_READABLE[name];
    return {
      id: name,
      name: proj?.title || name,
      year: proj?.year || "",
      tags: proj?.tags || [],
      short: readable?.short || "",
      highlights: readable?.highlights || [],
      impact: readable?.impact || "",
    };
  });
  const sourceText = data.map((d) => `${d.name} (${d.year})`).join("; ");
  return makeEvidence("get_projects", data, sourceText);
}

export function get_project(args) {
  const { name } = args || {};
  if (!name) return makeEvidence("get_project", null, "");
  // Fuzzy match by name
  const normalized = name.toLowerCase();
  const match = PROJECT_ORDER.find(
    (n) =>
      n.toLowerCase().includes(normalized) ||
      (PROJECTS[n]?.title || "").toLowerCase().includes(normalized)
  );
  if (!match) return makeEvidence("get_project", null, "not_found");
  const proj = PROJECTS[match];
  const readable = PROJECT_READABLE[match];
  const data = {
    id: match,
    name: proj?.title || "",
    year: proj?.year || "",
    tags: proj?.tags || [],
    short: readable?.short || "",
    highlights: readable?.highlights || [],
    impact: readable?.impact || "",
  };
  return makeEvidence("get_project", data, `${data.name}: ${data.short}`);
}

export function get_skills(args) {
  const { category } = args || {};
  const groups = [
    { group: "AI / ML & Computer Vision", key: "ai_ml_cv", items: ["YOLO", "SAM 2.1", "TwinLiteNetPlus", "OCR/VLM", "OpenCV", "Camera Calibration", "Multi-Camera Tracking", "Deep Learning", "Model Optimization", "QLoRA", "MLflow"] },
    { group: "GenAI & Agentic AI", key: "genai_agentic", items: ["LLM Agents", "LLM Engineering", "RAG", "Agentic Workflows", "LLM Tool Calling", "MCP", "LangChain", "LlamaIndex", "Pydantic Schema Validation"] },
    { group: "Edge & Sensor Systems", key: "edge_sensor", items: ["NVIDIA Jetson", "Edge Inference", "ROS", "Radar Point Clouds", "Sensor Fusion", "Low-Latency Pipeline", "Multithreading"] },
    { group: "Inference Optimization", key: "inference_opt", items: ["TensorRT", "CUDA", "ONNX", "Model Optimization"] },
    { group: "Backend & APIs", key: "backend_apis", items: ["Python", "C++", "FastAPI", "Flask", "REST APIs", "Microservices", "Pydantic", "Celery"] },
    { group: "Databases & Caching", key: "databases", items: ["PostgreSQL", "SQLite", "Redis"] },
    { group: "Cloud & DevOps", key: "cloud_devops", items: ["Docker", "Kubernetes", "AWS EC2", "AWS Bedrock", "SageMaker", "Azure", "Google Cloud", "Nginx", "Git"] },
    { group: "Languages", key: "languages", items: ["Python", "C++", "C", "SQL", "TypeScript"] },
  ];
  const data = category
    ? groups.filter((g) => g.key === category || g.group.toLowerCase().includes(category.toLowerCase()))
    : groups;
  return makeEvidence("get_skills", data, `${data.length} skill groups`);
}

export function get_education() {
  const nodes = getByType("education");
  const data = nodes.map((n) => ({
    id: n.id,
    degree: n.attrs.degree,
    institution: n.attrs.institution,
    period: n.attrs.period,
  }));
  const sourceText = data.map((d) => `${d.degree} @ ${d.institution}`).join("; ");
  return makeEvidence("get_education", data, sourceText);
}

export function get_certifications() {
  const nodes = getByType("certification");
  const data = nodes.map((n) => ({ id: n.id, name: n.attrs.name }));
  const sourceText = data.map((d) => d.name).join("; ");
  return makeEvidence("get_certifications", data, sourceText);
}

// ---- find_evidence — graph traversal + BM25 over the KB text ----
// Uses the graph to find related nodes, and BM25 over structured text.
export async function find_evidence(args) {
  const { topic } = args || {};
  if (!topic) return makeEvidence("find_evidence", [], "no-topic");

  // Phase 1: graph traversal from capability/skill nodes matching the topic
  const graphResults = getEvidenceForTopic(topic);

  // Phase 2: BM25 over the structured text of relevant nodes
  const allText = [];
  const nodeMap = {};

  // Collect searchable text from relevant node types
  const relevantTypes = ["project", "experience", "capability", "skill"];
  relevantTypes.forEach((type) => {
    getByType(type).forEach((node) => {
      const text = Object.values(node.attrs).filter((v) => typeof v === "string").join(" ");
      if (text) {
        allText.push({ id: node.id, text, node });
        nodeMap[node.id] = node;
      }
    });
  });

  // Simple BM25 over allText
  const tokens = phraseAwareTokenize(topic);
  const docFreq = {};
  allText.forEach((doc) => {
    const docTokens = phraseAwareTokenize(doc.text);
    [...new Set(docTokens)].forEach((t) => { docFreq[t] = (docFreq[t] || 0) + 1; });
  });
  const N = allText.length;
  const idf = Object.fromEntries(Object.entries(docFreq).map(([t, df]) => [t, Math.log((N + 1) / (df + 1))]));

  const scores = allText.map((doc) => {
    const docTokens = phraseAwareTokenize(doc.text);
    const tf = {};
    docTokens.forEach((t) => { tf[t] = (tf[t] || 0) + 1; });
    let score = 0;
    tokens.forEach((term) => {
      if (!idf[term]) return;
      const tf_val = tf[term] || 0;
      score += idf[term] * (tf_val * 2) / (tf_val + 1.5); // k1=1.5
    });
    return { ...doc, score };
  });

  scores.sort((a, b) => b.score - a.score);
  const topResults = scores.slice(0, 4).filter((r) => r.score > 0);

  const data = topResults.map((r) => ({
    node_id: r.id,
    type: r.node.type,
    name: r.node.attrs?.name || r.id,
    score: r.score,
    summary: Object.values(r.node.attrs)
      .filter((v) => typeof v === "string")
      .slice(0, 2)
      .join(" · "),
  }));

  return makeEvidence(
    "find_evidence",
    { topic, results: data },
    `${data.length} results for "${topic}": ${data.map((d) => d.name).join(", ")}`
  );
}

// ---- Skill registry ----
const SKILL_MAP = {
  get_profile: { fn: get_profile, args: [] },
  get_contact: { fn: get_contact, args: [] },
  get_experience: { fn: get_experience, args: [] },
  get_projects: { fn: get_projects, args: [] },
  get_skills: { fn: get_skills, args: [] },
  get_education: { fn: get_education, args: [] },
  get_certifications: { fn: get_certifications, args: [] },
  find_evidence: { fn: find_evidence, args: ["topic"] },
};

export function hasSkill(name) {
  return name in SKILL_MAP;
}

export function getSkillSignature(name) {
  return SKILL_MAP[name] || null;
}

export { SKILL_MAP };
